### ISSUE TITLE
Class not found. Folder structure?

### ISSUE THREAD

**Issue by bobwinch** [rene-s/Seafile-PHP-SDK#10]
Hello there, 

Could you precise what the folder structure should be ?

I'm always getting a class not found error.

**Comment by rene-s** [comment]
Hello bobwinch, thanks for your interest in Seafile-PHP-SDK. I would like to help you, yet there is not much information for me to direct you in one direction or the other.

MDN has great guidelines on how to write useful bug reports or service requests:

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

Regards
Rene

**Comment by bobwinch** [comment]
Hello, and thank you for your answer. Indeed I did not give enough information.

I got a wamp installation with php 7 on windows 10.

I followed your installation guide step by step, and my folder (.seafile-php-sdk) structure looks like this :

/vendor
api-token.json
cfg.json
composer.json
composer.lock
index.php

My vhost is pointing to the folder I created according to your directives : .seafile-php-sdk. 

My index.php is just a copy of your example file create_file.php

That file gives me the following error : Fatal error: Fatal error: Class 'Monolog\Logger' not found in E:\Bitbucket projects\seafilephp\.seafile-php-sdk\index.php on line 15.

What do you think could be the issue?

Hope I gave you enough information this time.

**Comment by bobwinch** [comment]
Nevermind, just had to install monolog via composer, and add "use Seafile\Client\Http\Client;" to my index.php for it to work.

Now I'm stuck with a curl ssl error, but it does not seem related to your work.

Sorry for the disturbance.
