### ISSUE TITLE
How to get list item of a folder

### ISSUE THREAD

**Issue by vipera7** [rene-s/Seafile-PHP-SDK#15]
### Expected behaviour
Get a list of item from a folder
### Actual behaviour
I would like to list all items in a particular folder. I can list all item from the librairie.
### Other helpful information
I would like to see how to use the fonction if it exist.
#### Do you have permissions to create a new directory?
Yes
#### Do you have permissions to read the directory?
Yes
#### Does the Seafile server work OK otherwise?
Yes
#### Did you obtain an API token from the server and has it been stored correctly?
Yes
#### Which branch or tag of the Seafile-PHP-SDK are you using?
v.1.0.1
#### Which PHP version are you using?
PHP 5.6.32
#### What is the version of the Seafile server you are using?
6.1.2
#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64bits
#### Are there error messages in the Seafile server's log files? If so, please post them.
Nop

Thank you !

**Comment by rene-s** [comment]
Hi there, I will look into this soon. Will take some days though.

**Comment by vipera7** [comment]
Thank you for your reply !

**Comment by rene-s** [comment]
Just checked the README. How it is done is mentioned [there](https://github.com/rene-s/Seafile-PHP-SDK#list-files-and-directories-of-a-library). However, I will update the README in the next release for improved clarity.

```php
$directoryResource = new Directory($client);
$lib = $libraryResource->getById('some library ID of yours');
$items = $directoryResource->getAll($lib, '/'); // 2nd param is the name of the directory or '/' 

foreach ($items as $item) {
    printf("%s: %s (%d bytes)\n", $item->type, $item->name, $item->size);
}
```
You require a `$client` instance and a `$lib` instance of the library you are inquiring. Please refer to one of the example scripts on how to create them: https://github.com/rene-s/Seafile-PHP-SDK/tree/develop/bin/examples

Have fun

**Comment by vipera7** [comment]
It's works really nice ! Thank you rene-s :)
