### ISSUE TITLE
PSR-4 in composer and file names

### ISSUE THREAD

**Issue by twify93** [rene-s/Seafile-PHP-SDK#2]
Hello,
Yesterday I started to use your library and the first this I needed to do is run the provided tests. Apparently it doesn't work out of the box.
What I wanted to as is: Why do you use "MyClass.class.php" and you try to autoload the files using PSR-4 when this breaks the PSR-4 standard.
Also I found out that you load your namespace in composer.json  `"Seafile\\": "lib/"` when apparently from composer documentation:
> When autoloading a class like Foo\\Bar\\Baz a namespace prefix Foo\\ pointing to a directory src/ means that the autoloader will look for a file named src/Bar/Baz.php

[composer documentation for PSR-4](https://getcomposer.org/doc/04-schema.md#psr-4)

This also didn't autoload the classes inside and I needed to fix the issue with:
`"Seafile\\": "lib/Seafile"`

**Comment by twify93** [comment]
Sorry my bad, I cloned the project and not use it like composer package...

**Comment by ymc-sise** [comment]
Unfortunately his does not work out of the box in Symfony2 when installing with composer.phar require. The class map in the psr-4 is wrong and it does not match the psr-4 standards. So i can't use it for my project. Instead I use the classes I need with plain "require ..."
