### ISSUE TITLE
Upload file gives an error on remote server

### ISSUE THREAD

**Issue by vipera7** [rene-s/Seafile-PHP-SDK#20]
### Expected behaviour
Upload a file on a remote server where Seafile is installed.
### Actual behaviour
Seafile server throwing me an error. It's look like it's searching for server on localhost.

>  Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST http://127.0.0.1/seafhttp/upload-api/78808a1d-df6c-4239-83d5-053deb065df8` resulted in a `404 Not Found` response: <head> <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" (truncated...) in C:\wamp64\www\seafile\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

### Steps to reproduce the behaviour

```php
$client = new Client(
    [
        'base_uri' => "http://192.168.0.53:8000",
        'debug' => false,
        'headers' => [
            'Content-Type' => 'application/json',
            'Authorization' => "Token $token"
        ]
    ]
);
$fileResource = new File($client);
$libraryResource = new Library($client);
$lib = $libraryResource->getById('some_libID');
$folder = "/";
$url = "C:/wamp64/tmp/some_file";
$response = $fileResource->upload($lib, $url, $folder);
$uploadedFileId = json_decode((string)$response->getBody());
```

#### Do you have permissions to create a new directory?
Yes
#### Do you have permissions to read the directory?
Yes
#### Does the Seafile server work OK otherwise?
Yes
#### Did you obtain an API token from the server and has it been stored correctly?
Yes
#### Which branch or tag of the Seafile-PHP-SDK are you using?
v.1.0.1
#### Which PHP version are you using?
PHP 7.2
#### What is the version of the Seafile server you are using?
6.1.2
#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64bits
#### Are there error messages in the Seafile server's log files? If so, please post them.
Nop

**Comment by rene-s** [comment]
Hello, I currently have no clue why Guzzle may want to try to upload to 127.0.0.1 when you have the Seafile server running on 192.168.0.53. You may want to check your configuration.

Also please bear in mind that running the SDK on Windows is unsupported yet so you may encounter strange behaviour there.
