### ISSUE TITLE
class docblocks too verbose

### ISSUE THREAD

**Issue by dakira** [rene-s/Seafile-PHP-SDK#6]
It's pretty verbose (and uncommon in opensource projects) to have docblocks like this for every single class in the project:

```
/**
 * Seafile PHP SDK Test Case class
 *
 * PHP version 5
 *
 * @category  API
 * @package   Seafile\Tests
 * @author    Rene Schmidt DevOps UG (haftungsbeschränkt) & Co. KG <rene@reneschmidt.de>
 * @copyright 2015 Rene Schmidt DevOps UG (haftungsbeschränkt) & Co. KG <rene@reneschmidt.de>
 * @license   https://opensource.org/licenses/MIT MIT
 * @link      https://github.com/rene-s/seafile-php-sdk
 */
```

It's more than enough to have a license and copyright file in the project root. In the worst case it tells other developers that this is your baby and you are not interested in contributors. In the best case it's very verbose and distracting.

Anyway: this looks great so far. I'm looking forward to using this and to contributing!

**Comment by rene-s** [comment]
Hello Dakira,

the project's class docblocks need to be trimmed, I agree. There are indeed some distracting entries. On the other hand, I intend to illustrate my commitment and dedication to this project by putting author and copyright information in every file (and by other measures). I consider myself in good company in this regard.

I am aware that might deter some developers, but please don't :) On the contrary, the docblocks are there to document the code and provide meta information.

Looking forward to your contributions!

Regards
Rene

**Comment by dakira** [comment]
> Looking forward to your contributions!

Yeah, I'm gonna test this a lot and will write an adapter for [Flysystem](http://flysystem.thephpleague.com/) as soon as I can get to it. That way this can easily be used interchangably with other (cloud) storage solutions.
