### ISSUE TITLE
Why the file "api-token.json" of mine is null?

### ISSUE THREAD

**Issue by cjforzero** [rene-s/Seafile-PHP-SDK#8]

**Comment by rene-s** [comment]
Hello, I do not know. Did you run obtain_api_token.sh? What's the std output of the script?

**Comment by cjforzero** [comment]
Yes, I ran the obtain_api_token.sh, then it requested me to input my account, password and the Seafile  server hostname. After finishing them, it appeared a sentence and then closed rapidly. There was a Api-token.json file in the corresponding directory, but it was null.  ps: I sat up my own Seafile server and created a  account. The server is available.

**Comment by rene-s** [comment]
Please try the "direct" method using "mkdir" and "curl" as described here:

https://github.com/rene-s/Seafile-PHP-SDK#obtain-api-token

That's basically what the script does.

**Comment by rene-s** [comment]
Either way, if you cannot retrieve a token the way I have described I presume there is an issue with the Seafile server you are using. Please refer to the Seafile support forums: https://forum.seafile.com/
